#[macro_use] extern crate rocket;
#[macro_use] extern crate rocket_contrib;
#[macro_use] extern crate serde_derive;
#[macro_use] extern crate diesel;
extern crate chrono;
pub mod error;
pub mod db;
pub mod schema;
pub mod models;
//pub mod projects;
